version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.3.2
    ports: 
      - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

  postgres:
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: albert
      POSTGRES_USER: postgres
      POSTGRES_DB: response_automater
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./backend/database_init/init.sql:/docker-entrypoint-initdb.d/init_db.sql
    
  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./data/postgres_storage:/var/lib/pgadmin


  